[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
hook_source = '''
		let g:deoplete#enable_at_startup = 1
		let g:auto_complete_delay = 0
		inoremap <expr><tab> pumvisible() ? "\<C-n>" :
				\ neosnippet#expandable_or_jumpable() ?
				\ "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
hook_post_source = '''
		let g:deoplte#omni_patterns = {}
'''
on_i = 1
on_ft = 'python'


[[plugins]]
repo = 'Shougo/neosnippet'
depends	= ['neosnippet-snippets']
hook_source = '''
		imap <C-k> <Plug>(neosnippet_expand_or_jump)
		smap <C-k> <Plug>(neosnippet_expand_or_jump)
		xmap <C-k> <Plug>(neosnippet_expand_target)
		if has('conceal')
				set conceallevel=2 concealcursor=niv
		endif
'''
on_i	= 1
on_ft	= ['snippet']



[[plugnins]]
repo = 'lervag/vimtex'
hook_source = '''
		let g:vimtex_compiler_latexmk = {
		\	'background'	: 1,
		\	'build_dir'		: '',
		\	'continuous'	: 1,
		\	'options'		: [ ],
		\}
'''
on_ft 	= 'tex'
