[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/Unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
		let g:vimfiler_as_default_explorer = 1
		let g:vimfiler_safe_mode_by_default = 0
		autocmd FileType vimfiler nmap <buffer> <CR> <Plug>(vimfiler_expand_or_edit)
'''

[[plugins]]
repo = 'mklabs/split-term.vim'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
		nmap <C-_> <Plug>(caw:hatpos:toggle)
		vmap <C-_> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
		let g:lightline = {
				\ 'colorscheme' : 'seoul256',
				\ }
'''
[[plugins]]
repo = 'simeji/winresizer'


[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'machakann/vim-colorscheme-tatami'

[[plugins]]
repo = 'freeo/vim-kalisi'
